src/Entity/Tag.php
<?php

namespace App\Entity;

use App\Repository\TagRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation\Slug;
use Gedmo\Mapping\Annotation\Timestampable;

#[ORM\Entity(repositoryClass: TagRepository::class)]
class Tag
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    #[Timestampable(on: 'create')]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(enumType: StatusEnum::class)]
    private StatusEnum $status;


    #[ORM\Column(length: 255)]
    #[Slug(fields: ['name'])]
    private ?string $slug = null;

    /**
     * @var Collection<int, JobOffer>
     */
    #[ORM\ManyToMany(targetEntity: JobOffer::class, mappedBy: 'tags')]
    private Collection $jobOffers;

    #[ORM\ManyToOne(inversedBy: 'tags')]
    #[ORM\JoinColumn(nullable: false)]
    private ?SuperAdminJobConfig $superAdminJobConfig = null;

    public function __construct()
    {
        $this->jobOffers = new ArrayCollection();
    }

    public function getStatus(): StatusEnum
    {
        return $this->status;
    }

    public function setStatus(StatusEnum $status): self
    {
        $this->status = $status;
        return $this;
    }
    public function getStatusString(): string
    {
        return $this->status->value;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, JobOffer>
     */
    public function getJobOffers(): Collection
    {
        return $this->jobOffers;
    }

    public function addJobOffer(JobOffer $jobOffer): static
    {
        if (!$this->jobOffers->contains($jobOffer)) {
            $this->jobOffers->add($jobOffer);
            $jobOffer->addTag($this);
        }

        return $this;
    }

    public function removeJobOffer(JobOffer $jobOffer): static
    {
        if ($this->jobOffers->removeElement($jobOffer)) {
            $jobOffer->removeCategory($this);
        }

        return $this;
    }

    public function getSuperAdminJobConfig(): ?SuperAdminJobConfig
    {
        return $this->superAdminJobConfig;
    }

    public function setSuperAdminJobConfig(?SuperAdminJobConfig $superAdminJobConfig): static
    {
        $this->superAdminJobConfig = $superAdminJobConfig;

        return $this;
    }
}

src/Controller/RecruiterController.php
<?php

namespace App\Controller;

use App\Entity\Application;
use App\Entity\StatusApplicationEnum;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted('ROLE_RECRUITER')]
class RecruiterController extends AbstractController
{
    #[Route('/recruiter', name: 'app_recruiter')]
    public function index(): Response
    {
        return $this->render('recruiter/index.html.twig', [
            'controller_name' => 'RecruiterController',
        ]);
    }

    #[Route('/recruiter/application/action/{id}/{status}', name: 'app_recruiter_application_action')]
    public function recruiterApplicationUnderStudy(Application $application, string $status, EntityManagerInterface $em): Response
    {
        $statusApplication = StatusApplicationEnum::PENDING;

        switch ($status) {
            case 'under study':
                $statusApplication = StatusApplicationEnum::UNDER_STUDY;
                break;
            case 'accepted':
                $statusApplication = StatusApplicationEnum::ACCEPTED;
                break;
            case 'rejected':
                $statusApplication = StatusApplicationEnum::REJECTED;
                break;
        }
        $application->setStatus($statusApplication);

        $em->persist($application);
        $em->flush();

        $status = $application->getStatusString();

        $this->addFlash('success', "The application has changed status. It has been marked as $status");
        return $this->redirectToRoute('app_user_dashboard');
    }
    #[Route('/recruiter/application/{id}', name: 'app_recruiter_application')]
    public function recruiterApplication(Application $application): Response
    {

        $statusApplication =  ['under study', 'pending', 'accepted', 'rejected'];
        return $this->render('recruiter/application.html.twig', [
            'application' => $application,
            'statusApplication' => $statusApplication
        ]);
    }
}

templates/recruiter/application.html.twig
{% extends 'base.html.twig' %}

{% block title %}Application
{% endblock %}

{% block body %}


	<div class="container my-5">
		<div class='text-center mb-4'>
			<h1>Application of
				{{ application.candidate.user.firstname }}
				{{ application.candidate.user.lastname }}
			</h1>
			{% if application.candidate.user.thumbnail %}

				<img src="{{asset('uploads/user/'~ application.candidate.user.thumbnail)}}" width="200" height="200" class="rounded-circle" alt="">
			{% else %}

				<img src="/images/profile-default.jpg" width="200" height="200" class="rounded-circle" alt="">
			{% endif %}
		</div>
		<div class="text-center mx-auto mb-5 sticky-sm-top bg-light shadow-sm p-5 w-50">
			<h4 class="text-info">Mark application as :</h4>
			<div class="d-flex gap-4 justify-content-center">

				{% for status in statusApplication %}
					{% set statusClass = "warning" %}
					{% if status == "accepted" %}
						{% set statusClass = "success" %}
					{% elseif status == "under study" %}
						{% set statusClass = "info" %}
					{% elseif status == "rejected" %}
						{% set statusClass = "danger" %}
					{% endif %}
					{% if status != application.statusString %}

						<form action="{{path('app_recruiter_application_action', {id : application.id, status : status})}}" data-action="modal-confirmation#onSubmit" method="POST" {{stimulus_controller('modal-confirmation', { title : 'Do you want to mark this application as ' ~ status ~ '?', text: 'Candidate will be notified!', icon: 'warning', confirmButtonText: 'Yes a do', submitAsync: true } )}}>
							<input type="hidden" name="_token" value="{{ csrf_token('status') }}"/>
							<button class="btn btn-{{statusClass}}">
								{{status}}
							</button>
						</form>
					{% endif %}

				{% endfor %}

			</div>
		</div>

		<div class="w-25 mx-auto mb-4">
			<a href="{{path('app_resume_pdf', {id : application.candidate.id})}}" target="_blank">
				<div class=" p-4 bg-light rounded text-center shadow-sm ">
					<p>See the Resume</p>
					{{ ux_icon('bi:filetype-pdf', {height: 50, width: 50} )}}
				</div>
			</a>
		</div>

		<section class="bg-light rounded shadow-sm p-5 mb-5">
			<h2>Candidate's presentation</h2>
			<p>{{application.customPresentation}}</p>
		</section>
		<section class="bg-light rounded shadow-sm p-5">
			<h2>Candidate's motivational message</h2>
			<p>{{application.motivationalMessage}}</p>
		</section>


	</div>
{% endblock %}

templates/recruiter/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello RecruiterController!
{% endblock %}

{% block body %}
	<style>
		.example-wrapper {
			margin: 1em auto;
			max-width: 800px;
			width: 95%;
			font: 18px / 1.5 sans-serif;
		}
		.example-wrapper code {
			background: #F5F5F5;
			padding: 2px 6px;
		}
	</style>

	<div class="example-wrapper">
		<h1>Hello
			{{ controller_name }}! ✅</h1>

		This friendly message is coming from:
		<ul>
			<li>Your controller at
				<code>/Users/zamuahalera/Sites/jobteq/src/Controller/RecruiterController.php</code>
			</li>
			<li>Your template at
				<code>/Users/zamuahalera/Sites/jobteq/templates/recruiter/index.html.twig</code>
			</li>
		</ul>
	</div>
{% endblock %}